name: Auto changelog

on:
  pull_request:
    branches: [master, develop]
    types: [closed]

jobs:
  generate_changelog:
    name: Generate changelog for master branch
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v2
      - name: Insert PR into CHANGELOG.md
        env:
          CLOSED_AT: ${{ github.event.pull_request.closed_at}}
          PR_URL: ${{ github.event.pull_request.html_url}}
          NUMBER: ${{ github.event.pull_request.number }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          PR_TYPE=$(echo $PR_TITLE | cut -d"]" -f 1 | cut -d"[" -f 2)
          PR_SUB_TITLE=$(echo $PR_TITLE | cut -d"]" -f 2)
          LINE_INDEX=$(grep -o -a -m 1 -h -r -n $PR_TYPE CHANGELOG.md | head -1 | cut -d":" -f 1)
          if [ -z "$LINE_INDEX" ]
          then
            echo "PR_TYPE error"
          else
            echo ''"$PR_SUB_TITLE"' ***by '"$AUTHOR"'*** [#'"$NUMBER"']('"$PR_URL"')'
            sed -i ''"$LINE_INDEX"' a- '"$PR_SUB_TITLE"' ***by '"$AUTHOR"'*** [#'"$NUMBER"']('"$PR_URL"')' CHANGELOG.md
          fi
      - name: Commit CHANGELOG.md
        run: |
          git config --local user.email "d0177381@gmail.com"
          git config --local user.name "github-action-bot"
          git add CHANGELOG.md
          git commit -m ':bookmark: updated CHANGELOG.md'|| echo "No changes to CHANGELOG.md"
      - name: Push commit
        run: |
          git push
